### ISSUE TITLE
Add slides to introduce MicroPython at the start of the workshop

### ISSUE THREAD

**Issue by mattytrentini** [mattytrentini/micropython_workshop#13]

**Comment by HowManyOliversAreThere** [comment]
I believe this has now been resolved @mattytrentini ?

**Comment by mattytrentini** [comment]
Yes, resolved. See [PyLadies Workshop Slides](https://docs.google.com/presentation/d/1kBm8YsX7sYx8pFmNHL0b7HM2EFQUV3dxOUeKSYTgmHE).
It's going to have to be tailored a little for each workshop though.
