### ISSUE TITLE
Consider migrating tools (rshell and mpfshell) to using Mu

### ISSUE THREAD

**Issue by mattytrentini** [mattytrentini/micropython_workshop#14]
[Mu](https://codewith.mu/) looks more appropriate for beginners and ought to work consistently across the major platforms.
Note: Currently the beta is required for ESP8266/32 comms.

**Comment by HowManyOliversAreThere** [comment]
I believe the time for consideration is over and Mu is the future based on the very positive reaction from Rose, will look to implement necessary changes (at least targeting Windows)
