### ISSUE TITLE
Mention additional Linux install steps

### ISSUE THREAD

**Issue by HowManyOliversAreThere** [mattytrentini/micropython_workshop#32]
In order for communications to work on Linux, the `tty` must have the correct permissions set. This should be added to the Linux install instructions.

**Comment by HowManyOliversAreThere** [comment]
Add user to dialout group

**Comment by mattytrentini** [comment]
See #38

**Comment by HowManyOliversAreThere** [comment]
Resolved with #38 having been merged.
